### ISSUE TITLE
Parallel should be the default

### ISSUE THREAD

**Issue by krisnye** [dubbha/yall-scripts#2]
Mostly just want to comment that this program is good and useful, thanks for writing and sharing.

I would suggest that parallel be the default mode since sequentially running scripts is easy already and works just fine using && operation between them on both windows and unix based OS's.

The real problem is the lack of good way to run tasks in parallel. Using & starts a background process which is almost never what you want when running npm/yarn scripts.

That's the only real motivation for downloading a script runner like this.

One other thing that would be hugely useful that I will mention is if tasks are run in parallel, the outputs get interleaved with each other. It would be ideal to have the terminal split into separate vertical sections for each parallel task still running with their own header (the name of the script) and content section not interleaved with others.

**Comment by eagerestwolf** [comment]
I very much agree with @dubbha here. Given that I assume the name comes from "yarn all" (hence yall), that would imply that you want to run a series of scripts in order.
